use serde_json::{Value,json}; use sha2::{Sha256,Digest}; use std::{fs,path::PathBuf};
fn s<'a>(v:&'a Value,k:&str)->&'a str{v.get(k).and_then(Value::as_str).unwrap_or("")}
fn n(v:&Value,k:&str)->i64{v.get(k).and_then(Value::as_i64).unwrap_or(-1)}
fn sha(t:&str)->String{hex::encode(Sha256::digest(t.as_bytes()))}
fn load(k:&PathBuf,nm:&str)->Value{serde_json::from_slice(&fs::read(k.join(nm)).unwrap()).unwrap()}
fn canon(x:&Value)->String{let p=&x["primitives"];let m=&x["market"];let d=&x["declared"];let ev=p["events"].as_array().unwrap().iter().map(|e|s(e,"type")).collect::<Vec<_>>().join(",");format!("{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",s(x,"version"),s(&p["entity"],"id"),s(&p["authority"],"id"),s(&p["right"],"id"),s(m,"instrument_id"),s(m,"venue_id"),s(m,"seller_entity_id"),s(m,"buyer_entity_id"),n(m,"quantity"),n(m,"unit_price_minor"),n(m,"originator_bps"),s(m,"usage_action"),n(d,"gross_minor"),n(d,"originator_minor"),n(d,"seller_net_minor"),ev)}
fn valid(x:&Value)->bool{if s(x,"schema")!="entity-v3-polyglot-transaction-v1"||s(x,"version")!="3.0.0"{return false}let p=&x["primitives"];let m=&x["market"];let d=&x["declared"];if s(&p["authority"],"principal_entity_id")!=s(m,"seller_entity_id")||s(&p["right"],"grantor_entity_id")!=s(m,"seller_entity_id")||s(&p["right"],"subject_entity_id")!=s(&p["entity"],"id"){return false}let(q,pr,bps)=(n(m,"quantity"),n(m,"unit_price_minor"),n(m,"originator_bps"));if q<=0||pr<0||bps<0||bps>10000||s(m,"buyer_entity_id")==s(m,"seller_entity_id"){return false}if !p["right"]["actions"].as_array().unwrap().iter().any(|a|a.as_str()==Some(s(m,"usage_action"))){return false}let ex=["REGISTER","DELEGATE","GRANT_RIGHT","LIST","TRADE","SETTLE","ENTITLE","USE","VALUE"];let ev=p["events"].as_array().unwrap();if ev.len()!=ex.len(){return false}for(i,e)in ev.iter().enumerate(){if s(e,"type")!=ex[i]||n(e,"seq")!=i as i64+1{return false}}let g=q*pr;let o=g*bps/10000;if n(d,"gross_minor")!=g||n(d,"originator_minor")!=o||n(d,"seller_net_minor")!=g-o{return false}sha(&canon(x))==s(x,"state_root_sha256")}
fn main(){let repo=std::env::current_dir().unwrap();let kit=repo.join("conformance-kit");let good=load(&kit,"VALID_TRANSACTION.json");let man=load(&kit,"CONFORMANCE_MANIFEST.json");let rec=load(&kit,"RECOVERY_EXPORT.json");let exp=load(&kit,"EXPECTED_RESULT.json");let inv=man["invalid_vectors"].as_array().unwrap();let rej=inv.iter().filter(|v|!valid(&load(&kit,v.as_str().unwrap()))).count();let cs=rec["controller_entities"].as_array().unwrap().iter().map(|v|v.as_str().unwrap()).collect::<Vec<_>>().join(",");let rr=sha(&format!("{}|{}|{}|{}",s(&rec,"version"),s(&rec,"state_root_sha256"),cs,n(&rec,"recovery_epoch")));let result=sha(&format!("{}|{}|{}",s(&good,"state_root_sha256"),s(&rec,"recovery_root_sha256"),rej));let pass=valid(&good)&&rr==s(&rec,"recovery_root_sha256")&&s(&rec,"state_root_sha256")==s(&good,"state_root_sha256")&&rej==inv.len()&&result==s(&exp,"result_sha256");let out=json!({"implementation":"rust","pass":pass,"state_root_sha256":s(&good,"state_root_sha256"),"recovery_root_sha256":s(&rec,"recovery_root_sha256"),"invalid_vectors_rejected":rej,"result_sha256":result});fs::create_dir_all(repo.join("qualification")).unwrap();fs::write(repo.join("qualification/result.json"),serde_json::to_vec_pretty(&out).unwrap()).unwrap();println!("{}",serde_json::to_string_pretty(&out).unwrap());if !pass{std::process::exit(2)}}

